# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
domain: 01luisrene.com
permalink: /articles/:title
title: 01luisrene
email: 01luisrene@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Soy técnico en Computación e Informática con muchos años de recorrido en el mundo informático; me encanta la programación web y el desarrollo móvil.

#baseurl: "http://01luisrene.com" # the subpath of your site, e.g. /blog

url: http://localhost:4000 # the base hostname & protocol for your site

twitter_username: 01luisrene
github_username:  01luisrene

# Build settings
markdown: kramdown
