# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
permalink: /blog/:year/:month/:day/:title.htm
title: 01luisrene
email: 01luisrene[at]gmail.com
description: > # this means to ignore newlines until "baseurl:"
  01luisrene: es el nombre de usuario que utilizo en las redes soiales (Twitter, Facebook, Google+); este sitio web a sido desarrollado para poder compartir contenidos de algunos lenguajes de programación (HTML5, CSS3, JAVASCRIPT, RUBY), PREPROCESADORES y mucho más.
description_author: > # description author
  Hola, soy Técnico Computación e Informática, me gusta el desarrollo Front End (HTM5, CSS3, JAVASCRIPT), me encanta aprender programación web ya que es el futuro.
domain: http://01luisrene.com
url: http://localhost:4000 # the base hostname & protocol for your site

twitter_username: 01luisrene
github_username:  01luisrene

# Build settings
markdown: kramdown

google_analytics_id: UA-73408981-1
